### ISSUE TITLE
Switch Function

### ISSUE THREAD

**Issue by shammayounus** [oe2015/M5-Atom-group-18#11]
I've tried writing the code for the second part of Part I, and I've tried to use a switch function in order to implement the mode switching similarly to how we used the function for the first part of Part I. However, this appears to not be working so far, and I think it might be due to the fact that we need to integrate tilting into the mode switching. Anyone knows how to resolve this?

**Comment by splabbit** [comment]
Reference to device orientation (tilting): https://patriot-geek.blogspot.com/2020/05/atom-matrix-using-mpu6886-accelerometer.html

**Comment by shammayounus** [comment]
Thank you!
